runtime: go
api_version: go1.8

handlers:
- url: /.*
  script: _go_app

#handlers:
#- url: /(.*\.(html|gif|png|jpeg|jpg|js))$
#  static_files: dist/\1
#  upload: dist\.(html|gif|png|jpeg|jpg|js)$
#  application_readable: true

